export const quizzes = [
  {
    question: 'What is your organization`s greatest strength?',
    samples: [
      'Always being there for people',
      'Following your gut instincts',
      'Having tons of imagination',
      'Having a magnetic, charismatic personality',
      'Protecting customers/clients',
      'Being curious and asking questions',
    ],
    answers: [
      'The Caregiver',
      'The Everyman',
      'The Creator',
      'The Lover',
      'The Ruler',
      'The Sage',
    ],
  },
  {
    question:
      'Which employee is most likely to win employee of the year at your company?',
    samples: [
      'Someone who works late and does the right thing',
      'Someone who is disciplined and focused',
      'Someone who is unique and questions the status quo',
      'Someone who can step up and take charge',
      'Someone who is passionate about your vision/mission',
      'Someone who makes work fun and always sparks clever ideas',
    ],
    answers: [
      'The Hero',
      'The Ruler',
      'The Outlaw',
      ['The Ruler', 'The Hero'],
      ['The Lover', 'The Magician'],
      ['The Jester', 'The Creator'],
    ],
  },
  {
    question: 'Which tone best fits what you want your brand to be?',
    samples: [
      'Optimistic',
      'Approachable',
      'Strong',
      'Practical',
      'Aspirational',
      'Passionate',
    ],
    answers: [
      ['The Innocent', 'The Explorer'],
      ['The Everyman', 'The Caregiver'],
      ['The Ruler', 'The Hero'],
      ['The Everyman', 'The Sage'],
      ['The Magician', 'The Hero'],
      ['The Lover', 'The Creator'],
    ],
  },
  {
    question: 'Which of these would be the worst thing for your brand?',
    samples: [
      'Being seen as “too corporate”, “out of touch” and “like everyone else”',
      'Being trapped in an old way of doing things and never changing',
      'Creating a new product/service that doesn’t do what we promised and fails',
      'Your actions causing negative outcomes in your customers’ lives',
      'Being seen as boring or irrelevant',
      'Providing bad information or making uninformed decisions',
    ],
    answers: [
      ['The Outlaw', 'The Creator'],
      ['The Explorer', 'The Magician'],
      ['The Innocent', 'The Everyman'],
      ['The Caregiver', 'The Ruler'],
      ['The Jester', 'The Everyman'],
      ['The Sage', 'The Ruler'],
    ],
  },
  {
    question: 'Our customers would say that we were…',
    samples: [
      'Straightforward and trustworthy',
      'Like a good friend to them',
      'Pioneers in our field',
      'Cutting-edge and innovative',
      'A group of miracle-workers',
      'Helpful and service-minded',
    ],
    answers: [
      ['The Everyman', 'The Caregiver'],
      ['The Lover', 'The Caregiver'],
      ['The Explorer', 'The Magician'],
      ['The Innovator', 'The Magician'],
      ['The Magician', 'The Hero'],
      ['The Caregiver', 'The Everyman'],
    ],
  },
  {
    question: 'Which of these types of content are you most drawn to?',
    samples: [
      'Motivational quotes about business success',
      'Listicles or videos packed with new business tactics to try',
      'Interesting case studies or articles about business leaders',
      'New meet-ups, groups or networking events',
      'Memes or funny videos about your industry',
      'Well-researched articles, reports or infographics',
    ],
    answers: [
      ['The Hero', 'The Magician'],
      ['The Innovator', 'The Explorer'],
      ['The Sage', 'The Ruler'],
      ['The Explorer', 'The Lover'],
      ['The Jester', 'The Outlaw'],
      ['The Sage', 'The Creator'],
    ],
  },
  {
    question: 'How does your brand, product, or service help people?',
    samples: [
      'It makes people feel good about themselves.',
      'It motivates people to achieve more',
      'It breaks conventions and challenges the status quo',
      'It offers freedom or an escape from the mundane',
      'It leads the way in an important field',
      'It educates people so they can reach their full potential',
    ],
    answers: [
      ['The Lover', 'The Caregiver'],
      ['The Hero', 'The Magician'],
      ['The Outlaw', 'The Creator'],
      ['The Explorer', 'The Outlaw'],
      ['The Leader', 'The Innovator'],
      ['The Sage', 'The Teacher'],
    ],
  },
  {
    question:
      'If you look ahead 5-10 years, how would you define your success?',
    samples: [
      'Developed strong relationships with our customers',
      'Created something of enduring value to society or culture',
      'Made people’s dreams come true',
      'Forged a common link between diverse communities',
      'Helped many people live better lives',
      'Gave people a little slice of paradise in their lives',
    ],
    answers: [
      ['The Lover', 'The Caregiver'],
      ['The Creator', 'The Magician'],
      ['The Magician', 'The Hero'],
      ['The Explorer', 'The Ruler'],
      ['The Caregiver', 'The Everyman'],
      ['The Innocent', 'The Lover'],
    ],
  },
  {
    question:
      'Which of these statements best describes what sets you apart from the competition?',
    samples: [
      'We stand by our values and strive for good',
      'We create and foster strong relationships',
      'We’re not afraid to shake things up and create change',
      'We know how to turn a problem into a solution',
      'We really care about our customers/clients',
      'We have the knowledge and experience it takes to do a great job',
    ],
    answers: [
      ['The Caregiver', 'The Innocent'],
      ['The Lover', 'The Caregiver'],
      ['The Outlaw', 'The Innovator'],
      ['The Magician', 'The Hero'],
      ['The Caregiver', 'The Everyman'],
      ['The Sage', 'The Ruler'],
    ],
  },
  {
    question: 'Which of these do you believe to be most true about the world?',
    samples: [
      'You have to work hard to get what you want',
      'Being uncomfortable inspires growth',
      'Creativity is just connecting things',
      'You can overcome any challenge by setting clear goals',
      'Happiness comes from finding balance within ourselves',
      'Life is too short to worry about things. Enjoy it',
    ],
    answers: [
      ['The Hero', 'The Ruler'],
      ['The Explorer', 'The Outlaw'],
      ['The Creator', 'The Innovator'],
      ['The Hero', 'The Magician'],
      ['The Caregiver', 'The Everyman'],
      ['The Jester', 'The Lover'],
    ],
  },
];
